[package]
edition = "2021"
name = "lura-syntax"
version = "0.0.1"

include = [
  "generated_src/*",
]

[dependencies]
tree-sitter = "~0.20.10"
tree-sitter-lura = "0.0.7"
type-sitter-lib = {git = "https://github.com/Jakobeha/type-sitter.git"}
